#!/bin/bash

echo "==================================="
echo "Zipsea Deployment Status Check"
echo "==================================="
echo ""
echo "Your backend has been successfully pushed to GitHub!"
echo ""
echo "Next steps:"
echo ""
echo "1. Go to Render Dashboard: https://dashboard.render.com"
echo ""
echo "2. Check the deployment status of 'zipsea-backend'"
echo ""
echo "3. Once deployed, your webhook endpoints will be available at:"
echo "   - https://zipsea-backend.onrender.com/webhooks/traveltek/cruiseline-pricing-updated"
echo "   - https://zipsea-backend.onrender.com/webhooks/traveltek/cruises-live-pricing-updated"
echo ""
echo "4. Health check endpoint:"
echo "   - https://zipsea-backend.onrender.com/health"
echo ""
echo "5. Configure environment variables in Render:"
echo "   Required (add these first):"
echo "   - CLERK_SECRET_KEY"
echo "   - CLERK_PUBLISHABLE_KEY"
echo "   - DATABASE_URL (will be auto-set by Render)"
echo "   - REDIS_URL (will be auto-set by Render)"
echo ""
echo "   Optional (can add later):"
echo "   - SENTRY_DSN"
echo "   - TRAVELTEK_FTP_HOST=ftpeu1prod.traveltek.net"
echo "   - TRAVELTEK_FTP_USER=<your-username>"
echo "   - TRAVELTEK_FTP_PASSWORD=<your-password>"
echo ""
echo "==================================="