version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: zipsea_dev
      POSTGRES_USER: zipsea_user
      POSTGRES_PASSWORD: zipsea_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zipsea_user -d zipsea_dev"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - zipsea_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - zipsea_network

  postgres_test:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: zipsea_test
      POSTGRES_USER: zipsea_test_user
      POSTGRES_PASSWORD: zipsea_test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zipsea_test_user -d zipsea_test"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - zipsea_network

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - zipsea_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis_password
    depends_on:
      - redis
    networks:
      - zipsea_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  postgres_test_data:
    driver: local

networks:
  zipsea_network:
    driver: bridge